version: "3.9"

services:
  web:
    networks:
      - bookstore_net
  db:
    networks:
      - bookstore_net

networks:
  bookstore_net:
    name: bookstore_net    # evita prefixo do diretório no nome da rede
    driver: bridge
